# Generated by Django 4.2.16 on 2024-09-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_coordinates_report_status_notification_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
