# Generated by Django 4.2.16 on 2024-09-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
