# Generated by Django 4.2.16 on 2024-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_departmentadmin_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image_path',
            field=models.CharField(max_length=255),
        ),
    ]
